version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: db.trijay
    working_dir: /application
    volumes:
      - .:/application
    environment:
      MYSQL_DATABASE: trijay
      MYSQL_USER: trijay
      MYSQL_PASSWORD: trijay
      MYSQL_ROOT_PASSWORD: trijay
    networks:
      - app-network
    ports:
      - "3300:3306"
  webserver:
    image: nginx:alpine
    restart: always
    container_name: api.trijay
    working_dir: /application
    volumes:
      - ./api:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7700:80
    networks:
      - app-network
  php-fpm:
    build: phpdocker/php-fpm
    container_name: laravel
    working_dir: /application
    volumes:
      - ./api:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    networks:
      - app-network
networks:
  app-network:
    driver: "bridge"